# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 0819e9131c7c393c14eceb12154094d8880835efb3c8e6288467d02cbc2e08e0241e2e290b4d252cd768eef6f7204b3ff6727462870082d25e42e327fe54b8d1

test:
  secret_key_base: c7c06302a8056c9c391cad2f5b3b3acd5d35840e62e6c9042a01c09b4461c82f596053782e7c7734b34b4e24b489e798618eccc3a0090e5f74d8be55f5e0cc8d

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
