# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: c87808384364bc30783961432a204dc9a8481770f9bc3ba1dc44c59d6fb3c42f622bd03d385c16d9dbc818ca437b20f5a1142dd3e0737472b61bb60bc0929eb5

test:
  secret_key_base: 5d7eb2f3fb8bb0857d31c8210b0e8ef3db7481a017e603e62d210a46d9d0d6f61165633192586bdb0a43bbfb094c9fecc6933c833d2a431fd844b47757a8e654

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
